// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarBillingSystem.Context;

#nullable disable

namespace StellarBillingSystem.Migrations
{
    [DbContext(typeof(BillingContext))]
    [Migration("20240627062626_initial14")]
    partial class initial14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilingSysytemModel", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryBasedDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID");

                    b.ToTable("SHCustomerBilling");
                });

            modelBuilder.Entity("CategoryMasterModel", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("SHCategoryMaster");
                });

            modelBuilder.Entity("CustomerMasterModel", b =>
                {
                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileNumber");

                    b.ToTable("SHCustomerMaster");
                });

            modelBuilder.Entity("DiscountCategoryMasterModel", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiscountPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("SHDiscountCategory");
                });

            modelBuilder.Entity("GSTMasterModel", b =>
                {
                    b.Property<string>("TaxID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CGST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGST")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaxID");

                    b.ToTable("SHGSTMaster");
                });

            modelBuilder.Entity("GodownModel", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofStocks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofStocksinRack")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("SHGodown");
                });

            modelBuilder.Entity("NetDiscountMasterModel", b =>
                {
                    b.Property<string>("NetDiscount")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetDiscount");

                    b.ToTable("SHNetDiscountMaster");
                });

            modelBuilder.Entity("PointsMasterModel", b =>
                {
                    b.Property<string>("PointsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointsID");

                    b.ToTable("SHPointsMaster");
                });

            modelBuilder.Entity("PointsReedemDetailsModel", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPoints")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("SHPointsReedemDetails");
                });

            modelBuilder.Entity("ProductMatserModel", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brandname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("SHProductMaster");
                });

            modelBuilder.Entity("RackMasterModel", b =>
                {
                    b.Property<string>("PartitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RackID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartitionID", "RackID");

                    b.ToTable("SHRackMaster");
                });

            modelBuilder.Entity("RackPatrionProductModel", b =>
                {
                    b.Property<string>("PartitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noofitems")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartitionID", "ProductID");

                    b.ToTable("SHRackPartionProduct");
                });

            modelBuilder.Entity("ReportModel", b =>
                {
                    b.Property<string>("ReportID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.ToTable("SHReportModel");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.LogsModel", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int?>("Att1")
                        .HasColumnType("int");

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogScreens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.ToTable("SBLogs");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.SignUpModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("SHSignUp");
                });

            modelBuilder.Entity("VoucherCustomerDetailModel", b =>
                {
                    b.Property<string>("VoucherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoucherID");

                    b.ToTable("SHVoucherDetails");
                });

            modelBuilder.Entity("VoucherMasterModel", b =>
                {
                    b.Property<string>("VoucherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VocherCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VocherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoucherID");

                    b.ToTable("SHVoucherMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
