// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarBillingSystem.Context;

#nullable disable

namespace StellarBillingSystem.Migrations
{
    [DbContext(typeof(BillingContext))]
    [Migration("20240814055917_initial74")]
    partial class initial74
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilingSysytemModel", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryBasedDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID", "BranchID");

                    b.ToTable("SHCustomerBilling");
                });

            modelBuilder.Entity("BranchMasterModel", b =>
                {
                    b.Property<string>("BracnchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("IsFranchise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BracnchID", "BranchName");

                    b.ToTable("SHBranchMaster");
                });

            modelBuilder.Entity("CategoryMasterModel", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID", "BranchID");

                    b.ToTable("SHCategoryMaster");
                });

            modelBuilder.Entity("CustomerMasterModel", b =>
                {
                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobileNumber", "BranchID");

                    b.ToTable("SHCustomerMaster");
                });

            modelBuilder.Entity("DiscountCategoryMasterModel", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiscountPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID", "BranchID");

                    b.ToTable("SHDiscountCategory");
                });

            modelBuilder.Entity("GSTMasterModel", b =>
                {
                    b.Property<string>("TaxID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CGST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGST")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaxID", "BranchID");

                    b.ToTable("SHGSTMaster");
                });

            modelBuilder.Entity("GodownModel", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DatefofPurchase")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierInformation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofStocks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID", "DatefofPurchase", "SupplierInformation", "BranchID");

                    b.ToTable("SHGodown");
                });

            modelBuilder.Entity("NetDiscountMasterModel", b =>
                {
                    b.Property<string>("NetID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetID", "BranchID");

                    b.ToTable("SHNetDiscountMaster");
                });

            modelBuilder.Entity("PointsMasterModel", b =>
                {
                    b.Property<string>("PointsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PointsID", "BranchID");

                    b.ToTable("SHPointsMaster");
                });

            modelBuilder.Entity("PointsReedemDetailsModel", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPoints")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID", "BranchID");

                    b.ToTable("SHPointsReedemDetails");
                });

            modelBuilder.Entity("ProductMatserModel", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BarcodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brandname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CGST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeiNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherTax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalAmount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID", "BranchID");

                    b.ToTable("SHProductMaster");
                });

            modelBuilder.Entity("RackMasterModel", b =>
                {
                    b.Property<string>("PartitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RackID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartitionID", "RackID", "BranchID");

                    b.ToTable("SHRackMaster");
                });

            modelBuilder.Entity("RackPatrionProductModel", b =>
                {
                    b.Property<string>("PartitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Noofitems")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartitionID", "ProductID", "BranchID");

                    b.ToTable("SHRackPartionProduct");
                });

            modelBuilder.Entity("ReportModel", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("BranchID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdateduser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("SHReportModel");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.BillingDetailsModel", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Lastupdateddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Totalprice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID", "ProductID", "BranchID");

                    b.ToTable("SHbilldetails");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.BillingMasterModel", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillDate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BillInsertion")
                        .HasColumnType("bit");

                    b.Property<string>("Billby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CGSTPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CGSTPercentageAmt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Lastupdateddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGSTPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SGSTPercentageAmt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Totalprice")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID", "BillDate", "BranchID");

                    b.ToTable("SHbillmaster");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.BillingPointsModel", b =>
                {
                    b.Property<string>("BillID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateofReedem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("NetPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Points")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillID", "CustomerNumber");

                    b.ToTable("SHBillingPoints");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.GenericReportModel", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Datecolumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDashboard")
                        .HasColumnType("bit");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportQuery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId", "BranchID");

                    b.ToTable("ShGenericReport");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.LogsModel", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Att1")
                        .HasColumnType("int");

                    b.Property<string>("LogDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogScreens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID", "BranchID");

                    b.ToTable("SBLogs");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.PaymentDetailsModel", b =>
                {
                    b.Property<string>("PaymentDiscription")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Lastupdateddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTransactionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentDiscription", "PaymentId", "BranchID");

                    b.ToTable("SHPaymentDetails");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.PaymentMasterModel", b =>
                {
                    b.Property<string>("BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Lastupdateddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillId", "PaymentId", "BranchID");

                    b.ToTable("SHPaymentMaster");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.ReedemHistoryModel", b =>
                {
                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateOfReedem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BillId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Lastupdateddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReedemPoints")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerNumber", "DateOfReedem", "BranchID");

                    b.ToTable("SHReedemHistory");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.ResourceTypeMasterModel", b =>
                {
                    b.Property<string>("ResourceTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ResourceTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResourceTypeID", "BranchID");

                    b.ToTable("SHresourceType");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.RoleAccessModel", b =>
                {
                    b.Property<string>("RollID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScreenID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Authorized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isdelete")
                        .HasColumnType("bit");

                    b.Property<string>("lastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollID", "ScreenID", "BranchID");

                    b.ToTable("SHRoleaccessModel");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.RollAccessMaster", b =>
                {
                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RollID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastupdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastupdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastupdateduser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID", "RollID", "BranchID");

                    b.ToTable("SHrollaccess");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.RollTypeMaster", b =>
                {
                    b.Property<string>("RollID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastupdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastupdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastupdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RollID", "BranchID");

                    b.ToTable("SHrollType");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.ScreenMasterModel", b =>
                {
                    b.Property<string>("ScreenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScreenId", "BranchID");

                    b.ToTable("SHScreenMaster");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.ScreenNameMasterModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SHScreenName");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.SignUpModel", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("SHSignUp");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.StaffAdminModel", b =>
                {
                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdProofName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastupdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastupdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID", "BranchID");

                    b.ToTable("SHStaffAdmin");
                });

            modelBuilder.Entity("StellarBillingSystem.Models.WebErrorsModel", b =>
                {
                    b.Property<string>("ErrodDesc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrDateTime")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ScreenName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ErrodDesc", "ErrDateTime", "ScreenName");

                    b.ToTable("SHWebErrors");
                });

            modelBuilder.Entity("VoucherCustomerDetailModel", b =>
                {
                    b.Property<string>("VoucherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoucherID", "BranchID");

                    b.ToTable("SHVoucherDetails");
                });

            modelBuilder.Entity("VoucherMasterModel", b =>
                {
                    b.Property<string>("VoucherID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdatedmachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VocherCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VocherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoucherID", "BranchID");

                    b.ToTable("SHVoucherMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
